from setuptools import setup, find_packages

setup(
    name='gradeadreamer',
    version='0.0.1',
    description='Text-to-3D',
    author="Trapoom Ukarapol & Kevin Pruvost",
    packages=find_packages(),
    package_data={"gradeadreamer": ["configs/*.yaml"]},
    install_requires=[
        'torch',
        'numpy',
        'tqdm',
        'omegaconf',
        'einops',
        'fastapi>=0.80',
        'huggingface_hub',
        'transformers',
        'open-clip-torch==2.24.0',
        'addict==2.4.0',
        'asttokens==2.4.1',
        'blinker==1.8.2',
        'cmake==3.29.3',
        'comm==0.2.2',
        'configargparse==1.7',
        'dash==2.17.0',
        'dash-core-components==2.0.0',
        'dash-html-components==2.0.0',
        'dash-table==5.0.0',
        'dataclasses-json==0.6.6',
        'decorator==5.1.1',
        'deprecated==1.2.14',
        'fastjsonschema==2.19.1',
        'flask==3.0.3',
        'ipywidgets==8.1.3',
        'jedi==0.19.1',
        'joblib==1.4.2',
        'jupyter-core==5.7.2',
        'jupyterlab-widgets==3.0.11',
        'lit==18.1.6',
        'marshmallow==3.21.2',
        'mypy-extensions==1.0.0',
        'nbformat==5.10.4',
        'nest-asyncio==1.6.0',
        'open3d',  # Version not specified in requirements.txt
        'parso==0.8.4',
        'pexpect==4.9.0',
        'plotly==5.22.0',
        'plyfile==1.0.3',
        'prompt-toolkit==3.0.45',
        'psutil==5.9.8',
        'ptyprocess==0.7.0',
        'pure-eval==0.2.2',
        'pygltflib==1.16.2',
        'pymeshlab==2023.12.post1',
        'pyquaternion==0.9.9',
        'retrying==1.3.4',
        'six==1.16.0',
        'stack-data==0.6.3',
        'tenacity==8.3.0',
        'threadpoolctl==3.5.0',
        'wrapt==1.16.0',
        # 'diff-gaussian-rasterization @ git+https://github.com/ashawkey/diff-gaussian-rasterization',
        # 'simple-knn @ git+https://github.com/camenduru/simple-knn/',
        # 'MVDream @ git+https://github.com/bytedance/MVDream',
        # 'nvdiffrast @ git+https://github.com/NVlabs/nvdiffrast/',
        # 'tiny-cuda-nn @ git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch',
        # 'kiuikit @ git+https://github.com/ashawkey/kiuikit',
    ],
    python_requires='>=3.9'
)
