seed: 0
text: A model of a house in Tudor style, no background, no stand
negative_text: ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor
  lighting, dull, unclear, cropped, lowres, low quality, artifacts, duplicate, morbid,
  mutilated, poorly drawn face, deformed, dehydrated, bad proportions
base_mesh: logs/house_tudor/house_tudor_mesh.obj
out_dir: house_tudor/appearance
random_textures: true
iter: 2000
batch: 4
coarse_iter: 300
save_interval: 100
texture_res: [2048, 2048]
train_res: [512, 512]
kd_min: [0.03, 0.03, 0.03]
kd_max: [0.97, 0.97, 0.97]
ks_min: [0, 0.08, 0]
ks_max: [0, 0.7, 0]
display:
  - {latlong: true}
  - {bsdf: kd}
  - {bsdf: ks}
  - {bsdf: normal}
envmap: data/irrmaps/mud_road_puresky_4k.hdr
env_scale: 2.0
train_background: black
validate: true
add_directional_text: true
camera_random_jitter: 0.2
fovy_range: [25.71, 45]
elevation_range: [-10, 45]
guidance_weight: 100
sds_weight_strategy: 1
early_time_step_range: [0.02, 0.98]
late_time_step_range: [0.02, 0.98]
mode: appearance_modeling
